version: '3.8'

services:
  regression:
    image: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/test_project
    # command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /test_project
    # environment:
#      - LOGIN=${LOGIN}
#      - PASSWORD=${PASSWORD}